### ISSUE TITLE
FIXME Count 1/ TODO Count 4

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-vue-address-form#14]
- [ ] TODO: specify propsData
       Commit: (77a94f6) Add core files.
       File:  [test/web/10-AddressForm.js:15](https://github.com/digitalbazaar/bedrock-vue-address-form/blob/master/test/web/10-AddressForm.js#L15)
       Dave Longley commented a year ago

  - [ ] TODO: consider moving to `bedrock-karma`?
       Commit: (77a94f6) Add core files.
       File:  [test/test.config.js:12](https://github.com/digitalbazaar/bedrock-vue-address-form/blob/master/test/test.config.js#L12)
       Dave Longley commented a year ago

  - [ ] FIXME: make configurable
       Commit: (77a94f6) Add core files.
       File:  [test/components/index.js:10](https://github.com/digitalbazaar/bedrock-vue-address-form/blob/master/test/components/index.js#L10)
       Dave Longley commented a year ago

  - [ ] TODO: Move to bedrock-web-forms
       Commit: (f377b11) Update label generation and use alpha-2 codes for countries.
       File:  [BrAddressForm.vue:330](https://github.com/digitalbazaar/bedrock-vue-address-form/blob/master/BrAddressForm.vue#L330)
       Ganesh Annan commented a year ago

  - [ ] TODO: $vm.el.something
       Commit: (77a94f6) Add core files.
       File:  [test/web/10-AddressForm.js:19](https://github.com/digitalbazaar/bedrock-vue-address-form/blob/master/test/web/10-AddressForm.js#L19)
       Dave Longley commented a year ago

       TODO Count          4
       FIXME Count         1
       Oldest Comment      a year ago
       Oldest Commenter    Dave Longley
       Oldest Comment      TODO: specify propsData

**Comment by aljones15** [comment]
This package also has several outstanding PRs some with bug fixes in them:

1. https://github.com/digitalbazaar/bedrock-vue-address-form/pull/5
  This was delayed due to:

> his PR isn't going to work until we have some kind of scss thing for the modules path. We should consider this when updating bedrock-views to help fix other dev issues.

2. https://github.com/digitalbazaar/bedrock-vue-address-form/pull/12
Fixes a fairly minor css bug

3. https://github.com/digitalbazaar/bedrock-vue-address-form/pull/13
Fixes more minor css bugs.
